import json
import re
from ollama import chat

def find_actions(text, allowed_actions):
    """Return the allowed actions referenced in `text`.

    Matching is case-insensitive and word-bounded, so "then STOP" and
    "then stop" both count, while "stopping" does not.
    """
    return {
        action
        for action in allowed_actions
        if re.search(rf"\b{re.escape(action)}\b", text, re.IGNORECASE)
    }

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.
SYSTEM_PROMPT = """
You are a Planner Agent in a multi-agent system. Your role is to decide HOW a robot should navigate, based on the requirements (the "what") provided by the Analyst Agent.

## Your Task
Given a requirements artifact produced by the Analyst Agent, produce a navigation plan that defines the robot's behavior. You must NOT question or change the requirements; treat them as fixed constraints.

## Input
You will receive a JSON object with this structure:
{
  "goal": "<the goal the robot must achieve>",
  "allowed_actions": ["FORWARD", "LEFT", "RIGHT", "STOP"],
  "safe_stop": <boolean>,
  "avoid_obstacles": <boolean>
}

## Output Format
Respond with ONLY a valid JSON object, no markdown, no code fences, no explanation. The JSON must have exactly these keys:

{
  "strategy": "<a concise textual strategy describing how the robot navigates toward the goal>",
  "decisions": [
    "<a decision rule written as a clear condition-action statement, using only allowed_actions>",
    ...
  ],
  "stop_point": "<a textual description of the condition or location at which the robot must stop>"
}

## Rules
1. You may ONLY use actions from the "allowed_actions" list (FORWARD, LEFT, RIGHT, STOP) inside the decisions.
2. Action names inside the decisions must be written in UPPERCASE, exactly as spelled in "allowed_actions" (write FORWARD, not "forward" or "move forward").
3. If "safe_stop" is true, the plan must include a STOP decision in the decisions list and clearly state it in the stop_point.
4. If "avoid_obstacles" is true, the decisions must include at least one rule that handles obstacle avoidance.
5. The strategy must be consistent with the goal and the allowed actions.
6. Each decision must be a clear, executable if/then style rule (e.g., "If an obstacle is detected ahead, then STOP").
7. Obstacle avoidance must turn the robot AWAY from the obstacle, never into it: an obstacle on the LEFT must trigger RIGHT, and an obstacle on the RIGHT must trigger LEFT.
8. Reaching the goal is the primary stop condition and must be stated as such in the stop_point. A STOP caused by an unavoidable obstacle is a fallback, not the normal behaviour.
9. Output ONLY the JSON object. Do not wrap it in markdown or add any text before or after.
"""

## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type.
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    if not isinstance(data, dict):
        raise ValueError(f"Invalid type: expected dict, got {type(data).__name__}")

    required_keys = {"strategy", "decisions", "stop_point"}
    data_keys = set(data.keys())
    missing = required_keys - data_keys
    if missing:
        raise ValueError(f"Missing required keys: {missing}")
    extra = data_keys - required_keys
    if extra:
        raise ValueError(f"Unexpected keys: {extra}")

    strategy = data["strategy"]
    if not isinstance(strategy, str) or not strategy.strip():
        raise ValueError("'strategy' must be a non-empty string")

    decisions = data["decisions"]
    if not isinstance(decisions, list) or len(decisions) == 0:
        raise ValueError("'decisions' must be a non-empty list")
    for i, d in enumerate(decisions):
        if not isinstance(d, str) or not d.strip():
            raise ValueError(f"'decisions[{i}]' must be a non-empty string")

    stop_point = data["stop_point"]
    if not isinstance(stop_point, str) or not stop_point.strip():
        raise ValueError("'stop_point' must be a non-empty string")

    allowed_actions = {"FORWARD", "LEFT", "RIGHT", "STOP"}
    for i, d in enumerate(decisions):
        if not find_actions(d, allowed_actions):
            raise ValueError(
                f"'decisions[{i}]' must reference at least one allowed action "
                f"from {allowed_actions}"
            )

    return True


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    user_content = json.dumps(requirement, ensure_ascii=False)
    
    response = chat(
        model="qwen3:8b",
        think=False,
        messages = [
            {"role": "system",
            "content": SYSTEM_PROMPT
            },
            {"role": "user", \
            "content": user_content
            },
        ]
    )

    raw_output = response["message"]["content"].strip()

    if raw_output.startswith("```"):
        raw_output = raw_output.split("```", 2)[1]
        if raw_output.startswith("json"):
            raw_output = raw_output[4:]
        raw_output = raw_output.strip()

    try:
        plan = json.loads(raw_output)
    except json.JSONDecodeError as e:
        raise ValueError(f"Planner Agent did not return valid JSON: {e}\nRaw output: {raw_output}")

    validate_plan(plan)

    return plan
